name: Test New Code

on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd ./Client/; mvn test
      
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd ./Server/; mvn test
      
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd ./Server/; mvn test
      

